apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  parallelism: 3 # 同时运行3个pods
  completions: 5 # 共5个pods
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: echo
          image: local/busybox:1.0
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"